#include<iostream>
using namespace std;

int main()
{
    int a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;
    cout<<"enter first number\n";
    cin>>a;
    cout<<"enter second number\n";
    cin>>b;
    cout<<"enter third number\n";
    cin>>c;
    cout<<"enter four numbe";
    cin>>d;
    cout<<"enter fifth number\n";
    cin>>e;
    cout<<"enter sixth number\n";
    cin>>f;
    cout<<"enter seventh number\n";
    cin>>g;
    cout<<"enter eighth number\n";
    cin>>h;
    cout<<"enter ninth number\n";
    cin>>i;
    cout<<"enter tenth number\n";
    cin>>j;
    cout<<"enter eleventh number\n";
    cin>>k;
    cout<<"enter twelvth number\n";
    cin>>l;
    cout<<"enter thirteenth number\n";
    cin>>m;
    cout<<"enter fourteeth number\n";
    cin>>n;
    cout<<"enter fifteenth number\n";
    cin>>o;
    cout<<"enter sixteenth number\n";
    cin>>p;
    cout<<"enter seventeeth number\n";
    cin>>q;
    cout<<"enter eighteenth number\n";
    cin>>r;
    cout<<"enter nineteeth number\n";
    cin>>s;
    cout<<"enter tweenth number\n";
    cin>>t;


    cout<<"here is your first number\n";
    cout<<a;
    cout<"here is your second number\n";
    coutt<<b;
    cout<<"here is your third number\n";
    cout<<c;
    cout<<"here is your fourth number\n";
    cout<<d;
    cout<<"here is your fivth number\n";
    cout<<e;
    cout<<"here is your sixth number\n";
    cout<<f;
    cout<<"here is your seventh number\n";
    cout<<g;
    cout<<"here is your eighth number\n";
    cout<<h;                            
    cout<<"heere is your ninth number\n";
    cout<<i;
    cout<<"here is your tenth number\n";
    cout<<j;
    cout<<"her is your eleventh number\n";
    cout<<k;
    cout<<"here is your twelveth number\n";
    cout<<l;
    cout<<"here is your thirteeth number\n";
    cout<<m;
    cout<<"here is your fourteenth number\n";
    cout<<n;
    cout<<"here is your  fifteenth number\n";
    cuot<<o;
    cout<<"here is your sixteenth number\n";
    cout<<p;
    cuot<<"here is your seventeenth number\n";
    cout<<q;
    cout<<"here is your eighteeth number\n";
    cout<<r;
    cout<<"here is your nineteenth number\n";
    cout<<s;
    cout<<|"here is your tweenth number\n";
    cout<<t;
    
     }
